package adapter

import (
	"context"
	"strings"
	"testing"
	"time"

	model "marrow/internal/model"
)

func TestVttToText_ManualCaptions_OneLinePerCue(t *testing.T) {
	vtt := `WEBVTT
Kind: captions
Language: en

00:00:27.103 --> 00:00:29.678
Good morning. How are you?

00:00:29.702 --> 00:00:31.105
(Audience) Good.

00:00:31.129 --> 00:00:32.797
It's been great, hasn't it?
`
	got := vttToText(vtt)
	want := "Good morning. How are you? (Audience) Good. It's been great, hasn't it?"
	if got != want {
		t.Errorf("vttToText() =\n%q\nwant:\n%q", got, want)
	}
}

// TestVttToText_AutoGeneratedRollingCaptions uses the real rolling-window
// shape YouTube's auto-captions actually produce (captured from a live
// video): each cue repeats the prior cue's line as its first line and
// appends newly-recognized words as its second line, plus zero-duration
// "flush" cues that repeat the prior line with a blank second line. Naively
// concatenating every line would badly duplicate text — this locks in that
// vttToText reconstructs the plain sentence instead.
func TestVttToText_AutoGeneratedRollingCaptions(t *testing.T) {
	vtt := `WEBVTT
Kind: captions
Language: en

00:00:00.160 --> 00:00:02.310 align:start position:0%

Right<00:00:00.400><c> now,</c><00:00:00.719><c> most</c><00:00:00.960><c> emergency</c> alert systems

00:00:02.310 --> 00:00:02.320 align:start position:0%
Right now, most emergency alert systems


00:00:02.320 --> 00:00:04.230 align:start position:0%
Right now, most emergency alert systems
struggle<00:00:02.720><c> to</c><00:00:02.879><c> keep</c> up with how fast and

00:00:04.230 --> 00:00:04.240 align:start position:0%
struggle to keep up with how fast and


00:00:04.240 --> 00:00:07.110 align:start position:0%
struggle to keep up with how fast and
unpredictable wildfires have become. But
`
	got := vttToText(vtt)
	want := "Right now, most emergency alert systems struggle to keep up with how fast and unpredictable wildfires have become. But"
	if got != want {
		t.Errorf("vttToText() =\n%q\nwant:\n%q", got, want)
	}
}

func TestVttToText_EmptyInput_ReturnsEmpty(t *testing.T) {
	if got := vttToText("WEBVTT\n"); got != "" {
		t.Errorf("expected empty transcript for a header-only file, got %q", got)
	}
}

func TestYoutubeCaptionResolver_Id(t *testing.T) {
	r := NewYoutubeCaptionResolver()
	if r.Id() != "youtube" {
		t.Errorf("expected id %q, got %q", "youtube", r.Id())
	}
}

// --- Real-infra tests below (per this repo's convention: hit real external
// services, not mocks). Requires network access and a working yt-dlp on
// PATH (already asserted at construction, see NewYoutubeCaptionResolver). ---

// tedTalkVideoID is a classic, unlikely-to-be-removed TED talk with
// manually authored English captions ("Do schools kill creativity?").
const tedTalkVideoID = "iG9CE55wbtY"

func TestYoutubeCaptionResolver_RealVideo_ReturnsTranscript(t *testing.T) {
	r := NewYoutubeCaptionResolver()

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	media, err := r.Resolve(ctx, model.MediaRef{Resolver: "youtube", Ref: tedTalkVideoID})
	if err != nil {
		t.Fatalf("Resolve failed: %v", err)
	}
	if media.Kind != model.MediaCaption {
		t.Errorf("expected MediaCaption, got %v", media.Kind)
	}
	if len(media.Buffer) == 0 {
		t.Fatal("expected a non-empty transcript for a talk known to have captions")
	}
	if !strings.Contains(string(media.Buffer), "creativity") {
		t.Errorf("expected the transcript to mention the talk's own topic, got preview: %q", string(media.Buffer[:min(200, len(media.Buffer))]))
	}
}
